### PR TITLE
Nicks branch

### PR DESCRIPTION
**Pull request by Ngomes1**

### CODE REVIEW

**Review by Grantb2134 — APPROVED** [review]

**Comment by JordyKieto** [comment]
@Ngomes1 can this branch be named after the feature you are adding?

**Comment by Ngomes1** [comment]
Good Morning Kieto,

I’m currently at work right now but will certainly make the changes however
in this particular push I’m just registering the app. In short I’m
wondering if it is best practice to create a branch for ever differing
function/ commit/ push created ? This would end up leading to many
differing branches. Please clarify exactly what you believe should be
general practice when creating a branch name in a situation where a project
is being mostly created through peer reviewing and no one section is being
designated to a person in the group, as per our instructions? Truly
appreciate your insight and advice so far and will say that we never went
into the details of general practices involving GitHub. In short, I will be
adding you as a reviewer as well as make changes as soon as possible!

Best Regards,
Nicholas Gomes

**Comment by JordyKieto** [comment]
> Good Morning Kieto, I’m currently at work right now but will certainly make the changes however in this particular push I’m just registering the app. In short I’m wondering if it is best practice to create a branch for ever differing function/ commit/ push created ? This would end up leading to many differing branches. Please clarify exactly what you believe should be general practice when creating a branch name in a situation where a project is being mostly created through peer reviewing and no one section is being designated to a person in the group, as per our instructions? Truly appreciate your insight and advice so far and will say that we never went into the details of general practices involving GitHub. In short, I will be adding you as a reviewer as well as make changes as soon as possible! Best Regards, Nicholas Gomes
> […](#)

Hey @Ngomes1 ,

Having a bunch of different branches isn't bad at all. I would recommend creating a branch for specific features / bugs.  For example, this pull request has multiple commits, which specify small changes. They don't all need their own branch, but I  agree with your approach of grouping related commits under one branch. The branch name should identify what the high level change is, ie) registering the app, updating models

I suggest this approach to help devs better understand what features are being added to the application, and at what point in time. So debugging is easier, and so that collaboration is easier

here is some reading material

[https://codingsight.com/git-branching-naming-convention-best-practices/](https://codingsight.com/git-branching-naming-convention-best-practices/)

[https://bocoup.com/blog/git-workflow-walkthrough-feature-branches](https://bocoup.com/blog/git-workflow-walkthrough-feature-branches)

**Comment by Ngomes1** [comment]
Thanks for the feedback! Will be looking at those documentation as well
soon.

**Pull request closed without merging**
